name: jitsi_meet_web_plugin
description: Jitsi Meet Web Plugin
version: 2.0.0
homepage: https://github.com/semimob/jitsi_meet

environment:
  sdk: ">=2.18.5 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.1.4
  jitsi_meet_platform_interface: ^2.0.0

  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.4
  meta: ^1.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      web:
        pluginClass: JitsiMeetPlugin
        fileName: jitsi_meet_web.dart
