name: jitsi_meet_platform_interface
description: A common platform interface for the jitsi meet plugin.
version: 2.0.1
homepage: https://github.com/semimob/jitsi_meet

environment:
  sdk: ">=2.18.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

